# bb_budget_monitoring_system/apps/admin_panel/ad_to_pdf_converter.py
"""
Activity Design to PDF Converter
Handles conversion of AD documents to PDF with BISU header
"""

import os
import subprocess
import tempfile
from django.core.files.base import ContentFile
from django.utils import timezone
from pathlib import Path
import logging

logger = logging.getLogger(__name__)


def generate_ad_pdf(ad):
    """
    Convert AD document to PDF with BISU header

    Handles three cases:
    1. Uploaded Word document (.docx, .doc) → Convert to PDF
    2. Uploaded PDF document → Copy as-is
    3. Form-based AD (no upload) → Generate PDF from data

    Returns: URL of generated PDF or None if failed
    """

    if not ad.uploaded_document:
        logger.warning(f"AD {ad.ad_number} has no uploaded document, skipping PDF generation")
        return None

    try:
        doc_path = ad.uploaded_document.path
        file_ext = Path(doc_path).suffix.lower()

        logger.info(f"Converting AD {ad.ad_number} document to PDF (format: {file_ext})")

        if file_ext == '.pdf':
            # Already PDF, just copy it
            logger.info("Document is already PDF, using as-is")
            return save_pdf_to_ad(ad, open(doc_path, 'rb').read())

        elif file_ext in ['.docx', '.doc']:
            # Convert Word to PDF
            logger.info("Converting Word document to PDF using LibreOffice")
            pdf_content = convert_word_to_pdf(doc_path)
            if pdf_content:
                return save_pdf_to_ad(ad, pdf_content)
            else:
                logger.error("Word to PDF conversion failed")
                return None

        else:
            logger.warning(f"Unsupported document format: {file_ext}")
            return None

    except Exception as e:
        logger.error(f"Error generating AD PDF: {str(e)}", exc_info=True)
        return None


def convert_word_to_pdf(word_path):
    """
    Convert Word document to PDF using LibreOffice
    Similar to PRE Excel conversion
    """
    with tempfile.TemporaryDirectory() as temp_dir:
        try:
            # LibreOffice command for Word to PDF
            cmd = [
                r"C:\Program Files\LibreOffice\program\soffice.exe",
                '--headless',
                '--invisible',
                '--nocrashreport',
                '--nodefault',
                '--nofirststartwizard',
                '--nolockcheck',
                '--nologo',
                '--norestore',
                '--convert-to', 'pdf:writer_pdf_Export',  # Writer PDF export
                '--outdir', temp_dir,
                word_path
            ]

            logger.info(f"Running LibreOffice conversion: {' '.join(cmd)}")

            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=60
            )

            if result.returncode != 0:
                logger.error(f"LibreOffice conversion failed: {result.stderr}")
                return None

            # Find generated PDF
            pdf_files = list(Path(temp_dir).glob('*.pdf'))
            if not pdf_files:
                logger.error("No PDF file generated by LibreOffice")
                return None

            pdf_path = pdf_files[0]
            logger.info(f"PDF generated successfully: {pdf_path}")

            # Read PDF content
            with open(pdf_path, 'rb') as f:
                return f.read()

        except subprocess.TimeoutExpired:
            logger.error("LibreOffice conversion timed out after 60 seconds")
            return None
        except Exception as e:
            logger.error(f"Error in Word to PDF conversion: {str(e)}", exc_info=True)
            return None


def save_pdf_to_ad(ad, pdf_content):
    """
    Save generated PDF to ActivityDesign model
    """
    try:
        # Generate filename
        timestamp = timezone.now().strftime('%Y%m%d_%H%M%S')
        filename = f"AD_{ad.ad_number}_{timestamp}.pdf"

        # Save to model
        ad.original_ad_pdf.save(
            filename,
            ContentFile(pdf_content),
            save=True
        )

        logger.info(f"PDF saved successfully for AD {ad.ad_number}: {ad.original_ad_pdf.url}")
        return ad.original_ad_pdf.url

    except Exception as e:
        logger.error(f"Error saving PDF to model: {str(e)}", exc_info=True)
        return None
