# Generated by Django 5.1.6 on 2025-03-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='item_name',
            new_name='entity_name',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='user',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='fund_cluster',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='office_section',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='pr_no',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='pr_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='purpose',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='responsibility_center_code',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='submitted_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
