# Generated by Django 5.1.3 on 2025-03-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
