# Generated by Django 5.1.6 on 2025-03-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0003_purchaserequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequestitems',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequestitems',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequestitems',
            name='stock_property_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequestitems',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequestitems',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
