# Generated by Django 5.1.6 on 2025-05-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0004_alter_purchaserequestitems_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='papp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
