# Generated by Django 5.1.6 on 2025-05-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0006_remove_purchaserequest_papp'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='papp',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
