# Generated by Django 5.1.6 on 2025-05-03 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0008_purchaserequest_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequestitems',
            name='total_amount',
        ),
    ]
