# Generated by Django 5.1.6 on 2025-05-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0010_budget_realignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_realignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='Pending', max_length=100),
        ),
    ]
