# Generated by Django 5.1.6 on 2025-08-08 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0011_budget_realignment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('prepared_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('certified_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_department_pres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
