# Generated by Django 5.1.6 on 2025-08-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0012_departmentpre'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentpre',
            name='approved_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departmentpre',
            name='approved_by_approving_officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departmentpre',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
