# Generated by Django 5.1.6 on 2025-08-10 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_remove_budgetallocation_assigned_user'),
        ('end_user_app', '0013_departmentpre_approved_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentpre',
            name='budget_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_pres', to='admin_panel.budgetallocation'),
        ),
    ]
