# Generated by Django 5.1.6 on 2025-08-10 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_remove_budgetallocation_assigned_user'),
        ('end_user_app', '0014_departmentpre_budget_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='budget_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='admin_panel.budgetallocation'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='source_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='source_item_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='source_pre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_purchase_requests', to='end_user_app.departmentpre'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='source_quarter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
