# Generated by Django 5.1.6 on 2025-08-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0016_activitydesign_alter_budget_realignment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydesign',
            name='approved_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitydesign',
            name='approved_by_approving_officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitydesign',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
