# Generated by Django 5.1.6 on 2025-08-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0018_remove_purchaserequest_papp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
