# Generated by Django 5.1.6 on 2025-08-30 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_budgetallocation_is_compiled'),
        ('end_user_app', '0019_alter_purchaserequest_pr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydesign',
            name='source_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='activitydesign',
            name='source_item_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitydesign',
            name='source_pre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_activity_designs', to='end_user_app.departmentpre'),
        ),
        migrations.AddField(
            model_name='activitydesign',
            name='source_quarter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='activitydesign',
            name='budget_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_designs', to='admin_panel.budgetallocation'),
        ),
    ]
