# Generated by Django 5.1.6 on 2025-08-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0022_fundsavailable_recommendingapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_by_approving_officer',
            field=models.BooleanField(default=False),
        ),
    ]
