# Generated by Django 5.1.6 on 2025-09-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0023_purchaserequest_approved_by_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentpre',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partially Approved', 'Partially Approved'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
