# Generated by Django 5.1.6 on 2025-09-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0024_alter_departmentpre_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='submitted_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partially Approved', 'Partially Approved'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
