# Generated by Django 5.1.6 on 2025-09-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0025_alter_purchaserequest_submitted_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('Submitted', 'Submitted')], default='draft', max_length=20),
        ),
    ]
