# Generated by Django 5.1.6 on 2025-09-10 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0026_alter_purchaserequest_pr_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRELineItemBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=255)),
                ('quarter', models.CharField(max_length=10)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('consumed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item_budgets', to='end_user_app.departmentpre')),
            ],
            options={
                'unique_together': {('pre', 'item_key', 'quarter')},
            },
        ),
    ]
