# Generated by Django 5.1.6 on 2025-09-10 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0027_prelineitembudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequestAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pre_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='end_user_app.prelineitembudget')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarter_allocations', to='end_user_app.purchaserequest')),
            ],
            options={
                'unique_together': {('purchase_request', 'pre_line_item')},
            },
        ),
    ]
