# Generated by Django 5.1.6 on 2025-09-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0028_purchaserequestallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='source_of_fund_display',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
