# Generated by Django 5.1.6 on 2025-09-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0029_purchaserequest_source_of_fund_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelineitembudget',
            name='reserved_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
