# Generated by Django 5.1.6 on 2025-09-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0030_prelineitembudget_reserved_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydesign',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
