# Generated by Django 5.1.6 on 2025-09-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0032_activitydesignallocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydesign',
            name='source_of_fund_display',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
