# Generated by Django 5.1.6 on 2025-09-19 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0033_activitydesign_source_of_fund_display'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PREBudgetRealignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_item_key', models.CharField(max_length=255)),
                ('source_quarter', models.CharField(blank=True, max_length=10, null=True)),
                ('target_item_key', models.CharField(max_length=255)),
                ('target_quarter', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_item_display', models.CharField(blank=True, max_length=500, null=True)),
                ('target_item_display', models.CharField(blank=True, max_length=500, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_realignment_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_realignment_requests', to=settings.AUTH_USER_MODEL)),
                ('source_pre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_realignments', to='end_user_app.departmentpre')),
                ('target_pre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_realignments', to='end_user_app.departmentpre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
