# Generated by Django 5.1.6 on 2025-09-20 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0034_prebudgetrealignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='approved_by_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='approved_by_approving_officer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='partial_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_realignment_partial_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prebudgetrealignment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Partially Approved', 'Partially Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
