# Generated by Django 5.1.6 on 2025-10-02 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0035_prebudgetrealignment_approved_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentpre',
            name='file_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentpre',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departmentpre',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='Upload PRE Excel file (.xlsx format only)', null=True, upload_to='pre_uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])]),
        ),
        migrations.AddField(
            model_name='departmentpre',
            name='validation_errors',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
