# Generated by Django 5.1.6 on 2025-10-09 07:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_remove_approvedbudget_file_format_and_more'),
        ('end_user_app', '0036_departmentpre_file_uploaded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PREDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_file', models.FileField(blank=True, null=True, upload_to='pre_drafts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])])),
                ('pre_filename', models.CharField(blank=True, max_length=255)),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budgetallocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'budget_allocation')},
            },
        ),
        migrations.CreateModel(
            name='PREDraftSupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='pre_draft_docs/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='end_user_app.predraft')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
