# Generated by Django 5.1.6 on 2025-11-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0037_predraft_predraftsupportingdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydesign',
            name='source_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='activitydesign',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
    ]
