# Generated by Django 5.1.6 on 2025-11-20 06:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0039_alter_activitydesign_source_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_realignment_admin_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='approved_documents',
            field=models.FileField(blank=True, help_text='Scanned approved documents uploaded by admin', null=True, upload_to='br_approved_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='final_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='final_approved_scan',
            field=models.FileField(blank=True, help_text='Scanned copy of signed budget realignment', null=True, upload_to='br_scanned/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='partially_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='partially_approved_pdf',
            field=models.FileField(blank=True, help_text='PDF generated from uploaded documents when partially approved', null=True, upload_to='br_pdfs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='q1_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='q2_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='q3_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='q4_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prebudgetrealignment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='prebudgetrealignment',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prebudgetrealignment',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Partially Approved', 'Partially Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BudgetRealignmentSupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='br_supporting_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls', 'jpg', 'jpeg', 'png'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_signed_copy', models.BooleanField(default=False, help_text='Is this a signed/approved copy?')),
                ('budget_realignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='end_user_app.prebudgetrealignment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
