# Generated by Django 5.1.6 on 2025-11-20 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0040_prebudgetrealignment_admin_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prebudgetrealignment',
            name='source_pre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_budget_realignments', to='end_user_app.departmentpre'),
        ),
        migrations.AlterField(
            model_name='prebudgetrealignment',
            name='target_pre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_budget_realignments', to='end_user_app.departmentpre'),
        ),
    ]
