# Generated by Django 5.1.6 on 2025-11-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_app', '0041_alter_prebudgetrealignment_source_pre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prebudgetrealignment',
            name='admin_approved_by',
        ),
        migrations.RemoveField(
            model_name='prebudgetrealignment',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='prebudgetrealignment',
            name='partial_approved_by',
        ),
        migrations.RemoveField(
            model_name='prebudgetrealignment',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='prebudgetrealignment',
            name='source_pre',
        ),
        migrations.RemoveField(
            model_name='prebudgetrealignment',
            name='target_pre',
        ),
        migrations.DeleteModel(
            name='BudgetRealignmentSupportingDocument',
        ),
        migrations.DeleteModel(
            name='PREBudgetRealignment',
        ),
    ]
