# Generated by Django 5.1.6 on 2025-03-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_is_active_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='Sample Full Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_approving_officer',
            field=models.BooleanField(default=False),
        ),
    ]
