# Generated by Django 5.1.6 on 2025-10-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
