# Generated by Django 5.1.6 on 2025-10-04 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvedbudget',
            options={'ordering': ['-created_at'], 'verbose_name': 'Approved Budget', 'verbose_name_plural': 'Approved Budgets'},
        ),
        migrations.RenameField(
            model_name='approvedbudget',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='approvedbudget',
            name='remaining_budget',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvedbudget',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvedbudget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='approvedbudget',
            name='supporting_document',
            field=models.FileField(help_text='Supporting document for the approved budget', upload_to='approved_budgets/%Y/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls'])]),
        ),
    ]
