# Generated by Django 5.1.6 on 2025-10-04 11:44

import apps.budgets.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_alter_approvedbudget_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedbudget',
            name='file_format',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='approvedbudget',
            name='supporting_document',
            field=models.FileField(help_text='Supporting document for the approved budget', upload_to=apps.budgets.models.approved_budget_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls'])]),
        ),
    ]
