# Generated by Django 5.1.6 on 2025-10-04 12:08

import apps.budgets.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_approvedbudget_file_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedbudget',
            name='file_format',
        ),
        migrations.RemoveField(
            model_name='approvedbudget',
            name='supporting_document',
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Supporting document (PDF, Word, Excel)', upload_to=apps.budgets.models.supporting_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_format', models.CharField(editable=False, max_length=10)),
                ('file_size', models.BigIntegerField(editable=False, help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('approved_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='budgets.approvedbudget')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supporting Document',
                'verbose_name_plural': 'Supporting Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
