# Generated by Django 5.1.6 on 2025-10-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_remove_approvedbudget_file_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentpre',
            name='fund_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='departmentpre',
            name='program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
