# Generated by Django 5.1.6 on 2025-10-21 13:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_alter_departmentpre_fund_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentpre',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when admin uploaded approved documents', null=True),
        ),
        migrations.AddField(
            model_name='departmentpre',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who uploaded the approved documents', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_approved_pres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmentpre',
            name='approved_documents',
            field=models.FileField(blank=True, help_text='Scanned approved documents uploaded by admin', null=True, upload_to='pre_approved_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
    ]
