# Generated by Django 5.1.6 on 2025-10-23 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_departmentpre_admin_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PRDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_file', models.FileField(blank=True, help_text='Uploaded PR document', null=True, upload_to='pr_drafts/%Y/%m/')),
                ('pr_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pr_draft', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PR Draft',
                'verbose_name_plural': 'PR Drafts',
                'db_table': 'pr_drafts',
            },
        ),
        migrations.CreateModel(
            name='PRDraftSupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Supporting document', upload_to='pr_draft_supporting/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='budgets.prdraft')),
            ],
            options={
                'db_table': 'pr_draft_supporting_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
