# Generated by Django 5.1.6 on 2025-10-23 00:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_prdraft_prdraftsupportingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='entity_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='fund_cluster',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='office_section',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='responsibility_center_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='source_line_item',
            field=models.ForeignKey(blank=True, help_text='Specific PRE line item used for funding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='budgets.prelineitem'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='source_of_fund_display',
            field=models.CharField(blank=True, help_text='Human-readable source of fund description', max_length=500),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='source_pre',
            field=models.ForeignKey(blank=True, help_text='Source PRE document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='budgets.departmentpre'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='final_approved_scan',
            field=models.FileField(blank=True, help_text='Scanned copy of signed PR', null=True, upload_to='pr_scanned/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='partially_approved_pdf',
            field=models.FileField(blank=True, help_text='PDF generated when partially approved', null=True, upload_to='pr_pdfs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='uploaded_document',
            field=models.FileField(blank=True, help_text='Uploaded PR document', null=True, upload_to='pr_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'doc', 'pdf'])]),
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_property_no', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('item_description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budgets.purchaserequest')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDesignAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount allocated from this line item', max_digits=15)),
                ('allocated_at', models.DateTimeField(auto_now_add=True, help_text='When the allocation was made')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this allocation')),
                ('activity_design', models.ForeignKey(help_text='The activity design being funded', on_delete=django.db.models.deletion.CASCADE, related_name='pre_allocations', to='budgets.activitydesign')),
                ('pre_line_item', models.ForeignKey(help_text='The PRE line item providing the funds', on_delete=django.db.models.deletion.PROTECT, related_name='ad_allocations', to='budgets.prelineitem')),
            ],
            options={
                'verbose_name': 'Activity Design Allocation',
                'verbose_name_plural': 'Activity Design Allocations',
                'db_table': 'activity_design_allocations',
                'ordering': ['-allocated_at'],
                'indexes': [models.Index(fields=['activity_design', 'pre_line_item'], name='activity_de_activit_62ab0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount allocated from this line item', max_digits=15)),
                ('allocated_at', models.DateTimeField(auto_now_add=True, help_text='When the allocation was made')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this allocation')),
                ('pre_line_item', models.ForeignKey(help_text='The PRE line item providing the funds', on_delete=django.db.models.deletion.PROTECT, related_name='pr_allocations', to='budgets.prelineitem')),
                ('purchase_request', models.ForeignKey(help_text='The purchase request being funded', on_delete=django.db.models.deletion.CASCADE, related_name='pre_allocations', to='budgets.purchaserequest')),
            ],
            options={
                'verbose_name': 'Purchase Request Allocation',
                'verbose_name_plural': 'Purchase Request Allocations',
                'db_table': 'purchase_request_allocations',
                'ordering': ['-allocated_at'],
                'indexes': [models.Index(fields=['purchase_request', 'pre_line_item'], name='purchase_re_purchas_75feec_idx')],
            },
        ),
    ]
