# Generated by Django 5.1.6 on 2025-10-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_purchaserequestallocation_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydesignallocation',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], default=1, help_text='Which quarter of the PRE line item is being used', max_length=2),
            preserve_default=False,
        ),
    ]
