# Generated by Django 5.1.6 on 2025-10-29 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0010_activitydesignallocation_quarter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequestSupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Supporting document file', upload_to='pr_supporting_docs/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='budgets.purchaserequest')),
            ],
            options={
                'db_table': 'purchase_request_supporting_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
