# Generated by Django 5.1.6 on 2025-10-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0011_purchaserequestsupportingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_documents',
            field=models.FileField(blank=True, help_text='Scanned signed copy uploaded by admin', null=True, upload_to='pr/approved_documents/'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes when uploading signed copy'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='final_approved_at',
            field=models.DateTimeField(blank=True, help_text='When admin uploaded signed copy (full approval)', null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='partially_approved_at',
            field=models.DateTimeField(blank=True, help_text='When admin partially approved', null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='partially_approved_pdf',
            field=models.FileField(blank=True, help_text='Auto-generated PDF when admin partially approves', null=True, upload_to='pr/partially_approved_pdfs/'),
        ),
    ]
