# Generated by Django 5.1.6 on 2025-10-31 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0012_purchaserequest_approved_documents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestsupportingdocument',
            name='is_signed_copy',
            field=models.BooleanField(default=False, help_text='True if this is the signed version uploaded by admin'),
        ),
        migrations.AddField(
            model_name='purchaserequestsupportingdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this document (admin for signed copies)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
