# Generated by Django 5.1.6 on 2025-11-02 05:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0013_purchaserequestsupportingdocument_is_signed_copy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydesign',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when admin uploaded approved documents', null=True),
        ),
        migrations.AddField(
            model_name='activitydesign',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who uploaded the approved documents', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_approved_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitydesign',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes during review'),
        ),
        migrations.AddField(
            model_name='activitydesign',
            name='approved_documents',
            field=models.FileField(blank=True, help_text='Scanned approved documents uploaded by admin', null=True, upload_to='ad_approved_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='activitydesign',
            name='purpose',
            field=models.TextField(blank=True, help_text='Purpose/justification for this activity'),
        ),
        migrations.AddField(
            model_name='activitydesign',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activitydesign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activitydesign',
            name='activity_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activitydesign',
            name='activity_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ActivityDesignSupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Supporting document file', upload_to='ad_supporting_docs/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_signed_copy', models.BooleanField(default=False, help_text='True if this is the signed version uploaded by admin')),
                ('activity_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='budgets.activitydesign')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this document (admin for signed copies)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_design_supporting_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ADDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_file', models.FileField(blank=True, help_text='Uploaded Activity Design document (.docx format only)', null=True, upload_to='ad_drafts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'doc'])])),
                ('ad_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_draft', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AD Draft',
                'verbose_name_plural': 'AD Drafts',
                'db_table': 'ad_drafts',
            },
        ),
        migrations.CreateModel(
            name='ADDraftSupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Supporting document', upload_to='ad_draft_supporting/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='budgets.addraft')),
            ],
            options={
                'db_table': 'ad_draft_supporting_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
