# Generated by Django 5.1.6 on 2025-11-10 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0014_activitydesign_admin_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydesign',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activitydesign',
            name='archive_type',
            field=models.CharField(blank=True, choices=[('FISCAL_YEAR', 'Fiscal Year Archive'), ('MANUAL', 'Manual Archive/Delete')], default='FISCAL_YEAR', max_length=20),
        ),
        migrations.AddField(
            model_name='activitydesign',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitydesign',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_activity_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitydesign',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='approvedbudget',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='approvedbudget',
            name='archive_type',
            field=models.CharField(blank=True, choices=[('FISCAL_YEAR', 'Fiscal Year Archive'), ('MANUAL', 'Manual Archive/Delete')], default='FISCAL_YEAR', max_length=20),
        ),
        migrations.AddField(
            model_name='approvedbudget',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvedbudget',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_approved_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvedbudget',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='archive_type',
            field=models.CharField(blank=True, choices=[('FISCAL_YEAR', 'Fiscal Year Archive'), ('MANUAL', 'Manual Archive/Delete')], default='FISCAL_YEAR', max_length=20),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_budget_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='departmentpre',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='departmentpre',
            name='archive_type',
            field=models.CharField(blank=True, choices=[('FISCAL_YEAR', 'Fiscal Year Archive'), ('MANUAL', 'Manual Archive/Delete')], default='FISCAL_YEAR', max_length=20),
        ),
        migrations.AddField(
            model_name='departmentpre',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentpre',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_department_pres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmentpre',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='archive_type',
            field=models.CharField(blank=True, choices=[('FISCAL_YEAR', 'Fiscal Year Archive'), ('MANUAL', 'Manual Archive/Delete')], default='FISCAL_YEAR', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_purchase_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
