# Generated by Django 5.1.6 on 2025-11-13 05:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0015_activitydesign_archive_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPRESupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Supporting document file (PDF, Word, Excel, Images)', upload_to='pre_supporting_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls', 'jpg', 'jpeg', 'png'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(editable=False, help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, help_text='Optional description of the document', max_length=500)),
                ('department_pre', models.ForeignKey(help_text='Link to PRE submission', on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='budgets.departmentpre')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PRE Supporting Document',
                'verbose_name_plural': 'PRE Supporting Documents',
                'db_table': 'department_pre_supporting_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
