# Generated by Django 5.1.6 on 2025-11-15 04:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0016_departmentpresupportingdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(help_text='Fiscal year of the savings', max_length=10)),
                ('department', models.CharField(help_text='Department name', max_length=255)),
                ('allocated_amount', models.DecimalField(decimal_places=2, help_text='Total amount allocated to department', max_digits=15)),
                ('pr_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount used by Purchase Requests', max_digits=15)),
                ('ad_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount used by Activity Designs', max_digits=15)),
                ('total_used', models.DecimalField(decimal_places=2, help_text='Total amount used (PR + AD)', max_digits=15)),
                ('savings_amount', models.DecimalField(decimal_places=2, help_text='Savings amount (Allocated - Used)', max_digits=15)),
                ('snapshot_date', models.DateTimeField(auto_now_add=True, help_text='When this snapshot was created')),
                ('quarter', models.CharField(blank=True, help_text='Q1, Q2, Q3, Q4, or Full Year', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this savings snapshot')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_budget_savings', to=settings.AUTH_USER_MODEL)),
                ('budget_allocation', models.ForeignKey(help_text='Link to the budget allocation', on_delete=django.db.models.deletion.CASCADE, related_name='savings_snapshots', to='budgets.budgetallocation')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_savings_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Savings',
                'verbose_name_plural': 'Budget Savings',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['fiscal_year', 'department'], name='budgets_bud_fiscal__35b76d_idx'), models.Index(fields=['-snapshot_date'], name='budgets_bud_snapsho_30adf3_idx')],
            },
        ),
    ]
