# Generated by Django 5.1.6 on 2025-11-17 03:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0017_budgetsavings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRELineItemSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Budget category (Personnel/MOOE/Capital)', max_length=255)),
                ('subcategory', models.CharField(blank=True, help_text='Budget subcategory if applicable', max_length=255)),
                ('item_name', models.CharField(help_text='Name of the budget line item', max_length=255)),
                ('q1_allocated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Q1 allocated amount', max_digits=15)),
                ('q1_consumed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Q1 consumed amount (PR + AD)', max_digits=15)),
                ('q1_surplus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Q1 unused/surplus amount', max_digits=15)),
                ('q2_allocated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Q2 allocated amount', max_digits=15)),
                ('q2_consumed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Q2 consumed amount (PR + AD)', max_digits=15)),
                ('q2_surplus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Q2 unused/surplus amount', max_digits=15)),
                ('q3_allocated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Q3 allocated amount', max_digits=15)),
                ('q3_consumed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Q3 consumed amount (PR + AD)', max_digits=15)),
                ('q3_surplus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Q3 unused/surplus amount', max_digits=15)),
                ('q4_allocated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Q4 allocated amount', max_digits=15)),
                ('q4_consumed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Q4 consumed amount (PR + AD)', max_digits=15)),
                ('q4_surplus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Q4 unused/surplus amount', max_digits=15)),
                ('total_allocated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total allocated across all quarters', max_digits=15)),
                ('total_consumed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total consumed across all quarters', max_digits=15)),
                ('total_surplus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total unused/surplus across all quarters', max_digits=15)),
                ('is_procurable', models.BooleanField(default=False, help_text='Whether this item requires procurement')),
                ('is_significant', models.BooleanField(default=False, help_text='True if surplus exceeds threshold (e.g., >₱5,000)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this line item savings record was created')),
                ('budget_savings', models.ForeignKey(help_text='Parent savings snapshot', on_delete=django.db.models.deletion.CASCADE, related_name='line_item_breakdowns', to='budgets.budgetsavings')),
                ('pre_line_item', models.ForeignKey(blank=True, help_text='Original PRE line item (may be null if deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_records', to='budgets.prelineitem')),
            ],
            options={
                'verbose_name': 'PRE Line Item Savings',
                'verbose_name_plural': 'PRE Line Item Savings',
                'ordering': ['-total_surplus', 'category', 'item_name'],
                'indexes': [models.Index(fields=['budget_savings', 'category'], name='budgets_pre_budget__bc57f0_idx'), models.Index(fields=['-total_surplus'], name='budgets_pre_total_s_626d95_idx'), models.Index(fields=['is_significant'], name='budgets_pre_is_sign_b6f0b5_idx')],
            },
        ),
    ]
