# Generated by Django 5.1.6 on 2025-11-18 13:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0018_prelineitemsavings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydesign',
            name='total_amount',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='activitydesignallocation',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Amount allocated from this line item', max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchaserequestallocation',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Amount allocated from this line item', max_digits=15),
        ),
    ]
