# Generated by Django 5.1.6 on 2025-11-18 13:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0019_alter_activitydesign_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedbudget',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='approvedbudget',
            name='remaining_budget',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='ad_amount_used',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='pr_amount_used',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='pre_amount_used',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='departmentpre',
            name='total_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='prelineitem',
            name='q1_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='prelineitem',
            name='q2_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='prelineitem',
            name='q3_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='prelineitem',
            name='q4_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='prereceipt',
            name='q1_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='prereceipt',
            name='q2_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='prereceipt',
            name='q3_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='prereceipt',
            name='q4_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=15),
        ),
    ]
