# Generated by Django 5.1.6 on 2025-11-19 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0020_alter_approvedbudget_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PRE_APPROVED', 'PRE Approved'), ('PR_APPROVED', 'Purchase Request Approved'), ('AD_APPROVED', 'Activity Design Approved'), ('PRE_REJECTED', 'PRE Rejected'), ('PR_REJECTED', 'Purchase Request Rejected'), ('AD_REJECTED', 'Activity Design Rejected'), ('ALLOCATION_CREATED', 'Allocation Created'), ('ALLOCATION_MODIFIED', 'Allocation Modified'), ('ALLOCATION_DELETED', 'Allocation Deleted'), ('REALIGNMENT_APPROVED', 'Budget Realignment Approved')], help_text='Type of transaction that caused the balance change', max_length=30)),
                ('amount_change', models.DecimalField(decimal_places=2, help_text='Amount added (positive) or deducted (negative) from budget', max_digits=12)),
                ('previous_balance', models.DecimalField(decimal_places=2, help_text='Balance before this transaction', max_digits=12)),
                ('new_balance', models.DecimalField(decimal_places=2, help_text='Balance after this transaction', max_digits=12)),
                ('related_document_type', models.CharField(blank=True, help_text='Type of related document (PRE, PR, AD, etc.)', max_length=20, null=True)),
                ('related_document_id', models.CharField(blank=True, help_text='ID or number of the related document', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this transaction occurred')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or context about this transaction')),
                ('allocation', models.ForeignKey(help_text='The budget allocation affected by this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to='budgets.budgetallocation')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who triggered this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Transaction Log',
                'verbose_name_plural': 'Budget Transaction Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['allocation', '-created_at'], name='budgets_bud_allocat_aefc28_idx'), models.Index(fields=['transaction_type', '-created_at'], name='budgets_bud_transac_90686b_idx'), models.Index(fields=['-created_at'], name='budgets_bud_created_424502_idx')],
            },
        ),
    ]
