# Generated by Django 5.1.6 on 2025-11-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0021_budgettransactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelineitem',
            name='source_type',
            field=models.CharField(choices=[('excel', 'From Excel Template'), ('manual', 'Manually Added')], default='excel', max_length=20),
        ),
    ]
