# Generated by Django 5.1.6 on 2025-11-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0022_add_source_type_to_prelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentpre',
            name='original_excel_pdf',
            field=models.FileField(blank=True, help_text='PDF converted from original uploaded Excel file (preserved snapshot)', null=True, upload_to='pre_pdfs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='departmentpre',
            name='partially_approved_pdf',
            field=models.FileField(blank=True, help_text='PDF generated from database when partially approved (includes custom line items)', null=True, upload_to='pre_pdfs/%Y/%m/'),
        ),
    ]
