# Generated by Django 5.1.6 on 2025-11-20 07:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0023_departmentpre_original_excel_pdf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PREBudgetRealignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Partially Approved', 'Partially Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('partially_approved_at', models.DateTimeField(blank=True, null=True)),
                ('final_approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_approving_officer', models.BooleanField(blank=True, default=False, null=True)),
                ('approved_by_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('admin_approved_at', models.DateTimeField(blank=True, null=True)),
                ('partially_approved_pdf', models.FileField(blank=True, help_text='PDF generated from uploaded documents when partially approved', null=True, upload_to='br_pdfs/%Y/%m/')),
                ('approved_documents', models.FileField(blank=True, help_text='Scanned approved documents uploaded by admin', null=True, upload_to='br_approved_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('final_approved_scan', models.FileField(blank=True, help_text='Scanned copy of signed budget realignment', null=True, upload_to='br_scanned/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('source_item_key', models.CharField(max_length=255)),
                ('source_quarter', models.CharField(blank=True, max_length=10, null=True)),
                ('target_item_key', models.CharField(max_length=255)),
                ('target_quarter', models.CharField(blank=True, max_length=10, null=True)),
                ('q1_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('q2_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('q3_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('q4_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source_item_display', models.CharField(blank=True, max_length=500, null=True)),
                ('target_item_display', models.CharField(blank=True, max_length=500, null=True)),
                ('admin_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_realignment_admin_approvals', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_realignment_approvals', to=settings.AUTH_USER_MODEL)),
                ('partial_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_realignment_partial_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_realignment_requests', to=settings.AUTH_USER_MODEL)),
                ('source_pre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_budget_realignments', to='budgets.departmentpre')),
                ('target_pre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_budget_realignments', to='budgets.departmentpre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetRealignmentSupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='br_supporting_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls', 'jpg', 'jpeg', 'png'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_signed_copy', models.BooleanField(default=False, help_text='Is this a signed/approved copy?')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('budget_realignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='budgets.prebudgetrealignment')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
