# Generated by Django 5.1.6 on 2025-11-21 14:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0026_departmentpreapproveddocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prelineitem',
            name='excel_row_number',
        ),
        migrations.RemoveField(
            model_name='prelineitem',
            name='is_custom_item',
        ),
        migrations.AlterField(
            model_name='activitydesign',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Review'), ('Partially Approved', 'Partially Approved'), ('Awaiting Admin Verification', 'Awaiting Admin Verification'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='departmentpreapproveddocument',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or notes'),
        ),
        migrations.AlterField(
            model_name='departmentpreapproveddocument',
            name='document',
            field=models.FileField(help_text='Signed/approved document (PDF or image scan)', upload_to='pre_approved_uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='departmentpreapproveddocument',
            name='document_type',
            field=models.CharField(choices=[('signed_pre', 'Signed PRE Document'), ('signed_supporting', 'Signed Supporting Document')], default='signed_pre', help_text='Type of approved document', max_length=50),
        ),
        migrations.AlterField(
            model_name='departmentpreapproveddocument',
            name='file_size',
            field=models.BigIntegerField(editable=False, help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='departmentpreapproveddocument',
            name='pre',
            field=models.ForeignKey(help_text='Link to PRE submission', on_delete=django.db.models.deletion.CASCADE, related_name='signed_approved_documents', to='budgets.departmentpre'),
        ),
        migrations.AlterField(
            model_name='departmentpreapproveddocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='End user who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_pre_approved_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prelineitem',
            name='source_type',
            field=models.CharField(choices=[('excel', 'From Excel Template'), ('manual', 'Manually Added')], default='excel', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Review'), ('Partially Approved', 'Partially Approved'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=30),
        ),
        migrations.AlterModelTable(
            name='departmentpreapproveddocument',
            table='department_pre_approved_documents',
        ),
    ]
