# Generated by Django 5.1.6 on 2025-11-21 18:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0027_remove_prelineitem_excel_row_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, help_text='When admin gave final approval after verification', null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who gave final approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_final_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='awaiting_verification',
            field=models.BooleanField(default=False, help_text='True when PR is awaiting admin verification of signed documents'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='end_user_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When end user uploaded signed documents', null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='original_pr_pdf',
            field=models.FileField(blank=True, help_text='PDF of original PR with BISU header (generated on partial approval)', null=True, upload_to='pr_original_pdfs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Review'), ('Partially Approved', 'Partially Approved'), ('Awaiting Admin Verification', 'Awaiting Admin Verification'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=50),
        ),
        migrations.CreateModel(
            name='PurchaseRequestApprovedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Signed/approved document (PDF or image scan)', upload_to='pr_approved_uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(editable=False, help_text='File size in bytes')),
                ('document_type', models.CharField(choices=[('signed_pr', 'Signed PR Document'), ('signed_supporting', 'Signed Supporting Document')], default='signed_pr', help_text='Type of approved document', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes')),
                ('purchase_request', models.ForeignKey(help_text='Link to PR submission', on_delete=django.db.models.deletion.CASCADE, related_name='signed_approved_documents', to='budgets.purchaserequest')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='End user who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_pr_approved_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PR Approved Document',
                'verbose_name_plural': 'PR Approved Documents',
                'db_table': 'purchase_request_approved_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
