# Generated by Django 5.1.6 on 2025-11-21 18:41

from django.db import migrations


def fix_cascade_constraint(apps, schema_editor):
    """
    Fix the foreign key constraint on BudgetTransactionLog.allocation
    to use CASCADE on delete instead of the current restriction.
    """
    # Drop the existing constraint
    schema_editor.execute(
        """
        ALTER TABLE budgets_budgettransactionlog
        DROP CONSTRAINT IF EXISTS budgets_budgettransa_allocation_id_53b5b28a_fk_budgets_b;
        """
    )

    # Add the constraint with CASCADE
    schema_editor.execute(
        """
        ALTER TABLE budgets_budgettransactionlog
        ADD CONSTRAINT budgets_budgettransa_allocation_id_53b5b28a_fk_budgets_b
        FOREIGN KEY (allocation_id)
        REFERENCES budgets_budgetallocation(id)
        ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0028_purchaserequest_admin_approved_at_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_cascade_constraint, reverse_code=migrations.RunPython.noop),
    ]
