# Generated by Django 5.1.6 on 2025-11-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0029_fix_transaction_log_cascade_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentpresupportingdocument',
            name='converted_pdf',
            field=models.FileField(blank=True, help_text='Auto-converted PDF version for preview (Excel/Word files)', null=True, upload_to='pre_supporting_docs_pdf/%Y/%m/'),
        ),
    ]
