# Generated by Django 5.1.6 on 2025-11-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0030_departmentpresupportingdocument_converted_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestsupportingdocument',
            name='converted_pdf',
            field=models.FileField(blank=True, help_text='Auto-converted PDF version for preview (Excel/Word files)', null=True, upload_to='pr_supporting_docs_pdf/%Y/%m/'),
        ),
    ]
