# Generated by Django 5.1.6 on 2025-11-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0031_purchaserequestsupportingdocument_converted_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestapproveddocument',
            name='converted_pdf',
            field=models.FileField(blank=True, help_text='Auto-converted PDF version for preview (image files)', null=True, upload_to='pr_approved_docs_pdf/%Y/%m/'),
        ),
    ]
