# Generated by Django 5.1.6 on 2025-11-22 08:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0032_purchaserequestapproveddocument_converted_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydesign',
            name='awaiting_verification',
            field=models.BooleanField(default=False, help_text='True when AD is awaiting admin verification of signed documents'),
        ),
        migrations.AddField(
            model_name='activitydesign',
            name='end_user_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When end user uploaded signed documents', null=True),
        ),
        migrations.AddField(
            model_name='activitydesign',
            name='original_ad_pdf',
            field=models.FileField(blank=True, help_text='Original AD document (converted to PDF if uploaded as DOCX)', null=True, upload_to='ad/original_pdfs/'),
        ),
        migrations.AddField(
            model_name='activitydesignsupportingdocument',
            name='converted_pdf',
            field=models.FileField(blank=True, help_text='Auto-converted PDF version for preview (Excel/Word files)', null=True, upload_to='ad_supporting_docs_pdf/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='activitydesign',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, help_text='When admin gave final approval', null=True),
        ),
        migrations.AlterField(
            model_name='activitydesign',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who gave final approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_final_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitydesign',
            name='approved_documents',
            field=models.FileField(blank=True, help_text='Scanned signed copy uploaded by admin (DEPRECATED - use signed_approved_documents)', null=True, upload_to='ad/approved_documents/'),
        ),
        migrations.AlterField(
            model_name='activitydesign',
            name='final_approved_scan',
            field=models.FileField(blank=True, help_text='Scanned copy of signed AD (DEPRECATED)', null=True, upload_to='ad_scanned/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='activitydesign',
            name='partially_approved_pdf',
            field=models.FileField(blank=True, help_text='Auto-generated PDF when admin partially approves', null=True, upload_to='ad/partially_approved_pdfs/'),
        ),
        migrations.AlterField(
            model_name='activitydesign',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Review'), ('Partially Approved', 'Partially Approved'), ('Awaiting Admin Verification', 'Awaiting Admin Verification'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=50),
        ),
        migrations.CreateModel(
            name='ActivityDesignApprovedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Signed/approved document (PDF or image scan)', upload_to='ad_approved_uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(editable=False, help_text='File size in bytes')),
                ('document_type', models.CharField(choices=[('signed_ad', 'Signed AD Document'), ('signed_supporting', 'Signed Supporting Document')], default='signed_ad', help_text='Type of approved document', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes')),
                ('converted_pdf', models.FileField(blank=True, help_text='Auto-converted PDF version for preview (image files)', null=True, upload_to='ad_approved_docs_pdf/%Y/%m/')),
                ('activity_design', models.ForeignKey(help_text='Link to AD submission', on_delete=django.db.models.deletion.CASCADE, related_name='signed_approved_documents', to='budgets.activitydesign')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='End user who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_ad_approved_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AD Approved Document',
                'verbose_name_plural': 'AD Approved Documents',
                'db_table': 'activity_design_approved_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
