# Generated by Django 5.1.6 on 2025-11-24 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0033_activitydesign_awaiting_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='end_user_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='end_user_uploaded_document',
            field=models.FileField(blank=True, help_text='Signed document uploaded by end user after partial approval', null=True, upload_to='br_end_user_uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='prebudgetrealignment',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Partially Approved', 'Partially Approved'), ('Awaiting Admin Verification', 'Awaiting Admin Verification'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
