# Generated by Django 5.1.6 on 2025-11-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0034_prebudgetrealignment_end_user_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrealignmentsupportingdocument',
            name='converted_pdf',
            field=models.FileField(blank=True, help_text='Auto-converted PDF for image/office document uploads', null=True, upload_to='br_converted_pdfs/%Y/%m/'),
        ),
    ]
