# Generated by Django 5.1.3 on 2025-02-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('instruction', 'Instruction'), ('research_ext', 'Research & Extension'), ('sports', 'Sports')], max_length=20, unique=True)),
                ('total_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
