# Generated by Django 5.1.3 on 2025-02-26 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='allocated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
