# Generated by Django 5.1.3 on 2025-02-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_budgetallocation_allocated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='remaining_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
