# Generated by Django 5.1.6 on 2025-05-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_budgetallocation_papp_audittrail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetallocation',
            name='papp',
            field=models.CharField(max_length=100),
        ),
    ]
