# Generated by Django 5.1.6 on 2025-05-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_budgetallocation_papp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetallocation',
            name='department',
            field=models.CharField(choices=[('instruction', 'Instruction'), ('research_ext', 'Research & Extension'), ('sports', 'Sports')], max_length=20),
        ),
    ]
