# Generated by Django 5.1.6 on 2025-05-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_budgetallocation_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetallocation',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='papp',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
