# Generated by Django 5.1.6 on 2025-08-05 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_approvedbudget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetallocation',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='budgetallocation',
            name='papp',
        ),
        migrations.RemoveField(
            model_name='budgetallocation',
            name='remaining_budget',
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='approved_budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.approvedbudget'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='allocated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='total_allocated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
