# Generated by Django 5.1.6 on 2025-08-06 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_alter_approvedbudget_assigned_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedbudget',
            name='assigned_user',
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='assigned_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='approved_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='admin_panel.approvedbudget'),
        ),
    ]
