# Generated by Django 5.1.6 on 2025-08-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_remove_approvedbudget_assigned_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetallocation',
            name='assigned_user',
        ),
    ]
