# Generated by Django 5.1.6 on 2025-08-19 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_remove_budgetallocation_assigned_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='audittrail',
            old_name='description',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='audittrail',
            old_name='department',
            new_name='model_name',
        ),
        migrations.AddField(
            model_name='audittrail',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='record_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('LOGIN', 'Logged In'), ('LOGOUT', 'Logged Out'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
