# Generated by Django 5.1.6 on 2025-08-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_rename_description_audittrail_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='is_compiled',
            field=models.BooleanField(default=False),
        ),
    ]
